<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="24LAP5CD019C4JP" failures="1" tests="5" name="Personal loan" time="0.078" errors="0" timestamp="2023-05-23T09:24:46 PET">
  <testcase classname="section16.day1" name="Demo" time="0.011">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at section16.day1.Demo(day1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="section16.day2" name="ploan" time="0.001"/>
  <testcase classname="section16.day4" name="LoginAPIHomeLoan" time="0.002"/>
  <testcase classname="section16.day4" name="MobileLoginHomeLoan" time="0.003"/>
  <testcase classname="section16.day4" name="WebloginHomeLoan" time="0.002"/>
  <testcase classname="section16.day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
